### ISSUE TITLE
Получение контекста

### ISSUE THREAD

**Issue by LazarenkoA** [maxstarkov/techlog-es#1]
Добрый день, а как вы поборолись с проблемой разбора свойств и значений? Просто разбить через "," не получится т.к. запятая может быть в значении, например контекста
```
Context='ОбщийМодуль.Вызов : ОбщийМодуль.СтандартныеПодсистемыВызовСервера.Модуль.ПриВыполненииСтандартныхПериодическихПроверокНаСервере
ОбщийМодуль.СтандартныеПодсистемыВызовСервера.Модуль : 260 : КонтрольДинамическогоОбновленияКонфигурацииСлужебный.ПриВыполненииСтандартныхПериодическихПроверокНаСервере(Параметры);
ОбщийМодуль.КонтрольДинамическогоОбновленияКонфигурацииСлужебный.Модуль : 13 : Параметры.Вставить("КонфигурацияБазыДанныхИзмененаДинамически",
ОбщийМодуль.КонтрольДинамическогоОбновленияКонфигурацииВызовСервера.Модуль : 12 : Возврат КонфигурацияБазыДанныхИзмененаДинамически()
ОбщийМодуль.СтандартныеПодсистемыСервер.Модуль : 1851 : Возврат ПараметрыСеанса.УстановленныеРасширения <> КонтрольныеСуммыРасширений();
ОбщийМодуль.СтандартныеПодсистемыСервер.Модуль : 1823 : Расширения = РасширенияКонфигурации.Получить();'
```

**Comment by maxstarkov** [comment]
Приветствую.

Контекст всегда заключен в одинарные или двойные кавычки. Бывало, что 1Сина выводит в контекст не двойную кавычку, а две одинарных - тогда ingest pipeline с таким не справляется и забирает текст только до второй одинарной кавычки. Но это происходит очень редко.
Может я не совсем понял вопрос, но в ingest pipeline https://github.com/maxstarkov/techlog-es/blob/master/techlog-pipeline.json есть узел в котором происходит обработка и извлечение контекста из записи события ТЖ.

**Comment by LazarenkoA** [comment]
> Контекст всегда заключен в одинарные или двойные кавычки. 

нет, много примеров где вообще нет кавычек, видимо только длинный контекст в кавычках

**Comment by maxstarkov** [comment]
Контекст без кавычек тоже обрабатывается: Context=(%{onecstr:Context}|%{DATA:Context},|%{GREEDYDATA:Context})
Если нет совпадения по шаблону контекста с кавычками, то просто забирается все до конца.
Проблемы встречал, когда в контексте есть две идущие подряд одинарные кавычки - тогда забирается только часть.
Такого не должно быть судя по документации к платформе, но бывает встречается.

**Comment by LazarenkoA** [comment]
спасибо, попробую

**Comment by maxstarkov** [comment]
Пожалуйста. Отпишитесь потом по результатам, буду благодарен.

**Comment by LazarenkoA** [comment]
в целом получилось, только вот время лога не коректно разбирается
https://github.com/maxstarkov/techlog-es/blob/90257baba32f91b94f2d6494fc11cca023ab86b7/techlog-pipeline.json#L16

Запись лога такая же
> 37:59.030002-0,SRVC,2,proc.... 

А ошибка вот такая 

> Text '83759.030002' could not be parsed at index 4

**Comment by maxstarkov** [comment]
Странно, а откуда символ "8" появляется в сообщении об ошибке? 
Судя по записи лога  - там нет такого символа в начале строки. Нужно проверить, что в поле message, filebeat точно шлет правильную запись лога ТЖ.

**Comment by LazarenkoA** [comment]
![image](https://user-images.githubusercontent.com/15386101/97216756-59fb9700-17d7-11eb-89f1-e2fa8a209baa.png)

**Comment by LazarenkoA** [comment]
эт что-то похоже с слешами связано (у нас linux), в другом примере такое 

> Text '20102700.log1057.818002' could not be parsed at index 8

будем шаманить дольше

**Comment by LazarenkoA** [comment]
получилось, это действительно из-за линукса, может добавишь отдельный файл для линукса в репу, мы изменили так
вместо
```json
"grok": {
    "field": "log.file.path",
    "patterns": [
     "%{INT:_ingest.tempyymmddhh}.log"
    ]
   }
```

так
```json
"grok" : {
          "field" : "log.file.path",
          "patterns" : [
            "(?<_ingest.tempyymmddhh>[0-9]{8}).log"
          ]
        }
```
иначе попадала 8 из части пути, а именно usr1cv**8**/log/minimal/rphost_22611222/20102623.log 

Еще замена слешей на линуксовые
```json
 "grok" : {
          "field" : "log.file.path",
          "patterns" : [
            "/%{USER:onectechlog.logname}/%{USER:onectechlog.process}_%{INT:onectechlog.pid}/%{INT}.log"
          ]
        }
```

**Comment by maxstarkov** [comment]
Да, все верно. Этот шаблон под windows. Попробую сделать универсальный шаблон.
Спасибо!
